GOOSE_PROVIDER: openrouter
GOOSE_MODEL: z-ai/glm-4.7
GOOSE_CLI_MIN_PRIORITY: 0.0
GOOSE_DISABLE_KEYRING: 'true'
GOOSE_MODE: smart_approve
SECURITY_PROMPT_ENABLED: true
GOOSE_CLI_THEME: ansi
extensions:
  developer:
    enabled: true
    type: builtin
    name: developer
    description: Code editing and shell access
    display_name: Developer Tools
    timeout: 60
    bundled: true
    available_tools: []
